name: Deploy Vite React TS to GitHub Pages

on:
  push:
    branches: [ main ]

# =========新增这一段权限声明=========
permissions:
  contents: write
  pages: write
  id-token: write
# ===================================

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ./convenience-store-simulator/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./convenience-store-simulator/package-lock.json') }}

      - name: Install dependencies
        run: |
          cd convenience-store-simulator
          npm install

      - name: Vite production build
        run: |
          cd convenience-store-simulator
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./convenience-store-simulator/dist